### ISSUE TITLE
测试结果低于论文Table1报告的val结果

### ISSUE THREAD

**Issue by DuZzzs** [zhangyp15/MonoFlex#7]
您好，我在kitti-split1上用单卡进行训练，batch_size=4，在val的3694张图上测试：
```
[2021-06-17 06:25:15,960] monoflex.inference INFO: metric = R40
[2021-06-17 06:25:15,961] monoflex.inference INFO:
Car AP@0.70, 0.70, 0.70:
bbox AP:93.1365, 88.1290, 80.6364
bev  AP:27.4066, 19.9626, 16.8124
3d   AP:19.3602, 13.9580, 11.9678
aos  AP:93.01, 87.77, 79.92
Car AP@0.70, 0.50, 0.50:
bbox AP:93.1365, 88.1290, 80.6364
bev  AP:61.1731, 45.9274, 40.7388
3d   AP:55.3238, 41.9672, 35.9666
aos  AP:93.01, 87.77, 79.92
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:52.8775, 44.4330, 37.8220
bev  AP:6.5744, 5.0258, 4.0656
3d   AP:5.9074, 4.2190, 3.2233
aos  AP:46.37, 38.43, 32.49
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:52.8775, 44.4330, 37.8220
bev  AP:21.2798, 17.0815, 13.9071
3d   AP:20.5831, 16.5574, 13.3822
aos  AP:46.37, 38.43, 32.49
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:55.2721, 36.1850, 33.6507
bev  AP:1.5678, 0.8645, 0.7968
3d   AP:1.2153, 0.3637, 0.3799
aos  AP:47.42, 30.75, 28.57
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:55.2721, 36.1850, 33.6507
bev  AP:11.4607, 5.7936, 5.4553
3d   AP:10.6146, 5.3862, 4.8811
aos  AP:47.42, 30.75, 28.57

[2021-06-17 06:25:16,132] monoflex.trainer INFO: Total training time: 21:24:51.903272 (0.8307 s / it), best model is achieved at iteration = 91872
```
低于论文中Table1的val ap3d_r40,：23.64 17.51 14.83，相差4个点左右。请问是我哪里设置的不对吗？谢谢

**Comment by zhangyp15** [comment]
1.  batch size 减小一半可能是主要的原因，因为 backbone、detection heads都包括了 batch norm 层，之后我们会做一些相关的测试，比如说多卡训练 + sync-bn来减少对 batch size 的敏感程度

2. 目前的训练还有一些不稳定，batch size 过小可能会进一步加剧梯度的不稳定性，造成性能比较差

3. 这是我们训练得到的一些结果，可以作为参考

  [2021-06-16 05:26:37,033] monoflex.inference INFO: metric = R40
  [2021-06-16 05:26:37,033] monoflex.inference INFO: 
  Car AP@0.70, 0.70, 0.70:
  bbox AP:96.4799, 90.8313, 85.2497
  bev  AP:32.7405, 24.0195, 20.6712
  3d   AP:23.2198, 17.1862, 15.1341
  aos  AP:96.19, 90.25, 84.25
  Car AP@0.70, 0.50, 0.50:
  bbox AP:96.4799, 90.8313, 85.2497
  bev  AP:68.3894, 51.0235, 46.0699
  3d   AP:63.6801, 47.2968, 42.5364
  aos  AP:96.19, 90.25, 84.25
  Pedestrian AP@0.50, 0.50, 0.50:
  bbox AP:63.8255, 55.0459, 47.7017
  bev  AP:9.4439, 7.3195, 6.1378
  3d   AP:8.9742, 6.8726, 5.7400
  aos  AP:58.57, 49.77, 43.01
  Pedestrian AP@0.50, 0.25, 0.25:
  bbox AP:63.8255, 55.0459, 47.7017
  bev  AP:29.5012, 23.8274, 19.8990
  3d   AP:27.9680, 23.1865, 19.3340
  aos  AP:58.57, 49.77, 43.01
  Cyclist AP@0.50, 0.50, 0.50:
  bbox AP:67.9108, 42.9276, 39.1897
  bev  AP:7.0621, 3.4214, 3.3636
  3d   AP:6.0866, 3.1231, 2.5338
  aos  AP:60.22, 37.46, 34.35
  Cyclist AP@0.50, 0.25, 0.25:
  bbox AP:67.9108, 42.9276, 39.1897
  bev  AP:23.2135, 12.6089, 11.4456
  3d   AP:22.0117, 11.9671, 10.8441
  aos  AP:60.22, 37.46, 34.35

**Comment by DuZzzs** [comment]
@zhangyp15 非常感谢。我去掉了backbone中的dcn，使用4卡，每张卡batch_size=6训练。后面可以更新下结果。

**Comment by zhangyp15** [comment]
BTW, validation set 应该是 3712 张图？

印象中 DCN 带来的提升还是挺大的，也是沿用了之前centernet等工作的backbone，直接去掉 dcn 效果也会不太好。另外多GPU的训练我们没有测试过，非常感谢你的尝试。

**Comment by DuZzzs** [comment]
我用的imagesets里val是3769张图，train是3712张。应该是从官网下载的，我再去核对下这里。
dcn在原centernet中提点1~2，不清楚在3d目标检测中的重要程度，去掉是为了后续做轻量化。

**Comment by BigTeacher-777** [comment]
> 我用的imagesets里val是3769张图，train是3712张。应该是从官网下载的，我再去核对下这里。
> dcn在原centernet中提点1~2，不清楚在3d目标检测中的重要程度，去掉是为了后续做轻量化。
> 多卡训练在val时报错：`torch.nn.modules.module.ModuleAttributeError: 'DistributedDataParallel' object has no attribute 'heads'`，还需要再调试下。非常感谢。



> 您好，我在kitti-split1上用单卡进行训练，batch_size=4，在val的3694张图上测试：
> 
> ```
> [2021-06-17 06:25:15,960] monoflex.inference INFO: metric = R40
> [2021-06-17 06:25:15,961] monoflex.inference INFO:
> Car AP@0.70, 0.70, 0.70:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:27.4066, 19.9626, 16.8124
> 3d   AP:19.3602, 13.9580, 11.9678
> aos  AP:93.01, 87.77, 79.92
> Car AP@0.70, 0.50, 0.50:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:61.1731, 45.9274, 40.7388
> 3d   AP:55.3238, 41.9672, 35.9666
> aos  AP:93.01, 87.77, 79.92
> Pedestrian AP@0.50, 0.50, 0.50:
> bbox AP:52.8775, 44.4330, 37.8220
> bev  AP:6.5744, 5.0258, 4.0656
> 3d   AP:5.9074, 4.2190, 3.2233
> aos  AP:46.37, 38.43, 32.49
> Pedestrian AP@0.50, 0.25, 0.25:
> bbox AP:52.8775, 44.4330, 37.8220
> bev  AP:21.2798, 17.0815, 13.9071
> 3d   AP:20.5831, 16.5574, 13.3822
> aos  AP:46.37, 38.43, 32.49
> Cyclist AP@0.50, 0.50, 0.50:
> bbox AP:55.2721, 36.1850, 33.6507
> bev  AP:1.5678, 0.8645, 0.7968
> 3d   AP:1.2153, 0.3637, 0.3799
> aos  AP:47.42, 30.75, 28.57
> Cyclist AP@0.50, 0.25, 0.25:
> bbox AP:55.2721, 36.1850, 33.6507
> bev  AP:11.4607, 5.7936, 5.4553
> 3d   AP:10.6146, 5.3862, 4.8811
> aos  AP:47.42, 30.75, 28.57
> 
> [2021-06-17 06:25:16,132] monoflex.trainer INFO: Total training time: 21:24:51.903272 (0.8307 s / it), best model is achieved at iteration = 91872
> ```
> 
> 低于论文中Table1的val ap3d_r40,：23.64 17.51 14.83，相差4个点左右。请问是我哪里设置的不对吗？谢谢

请问你后续训练的结果是多少，我保持跟作者一样的配置，得到的是跟你相近的结果

**Comment by DuZzzs** [comment]
@BigTeacher-777 去掉dla中的dcn，batch_size=6，单卡训练。val上结果：
```
[2021-06-19 12:10:34,456] monoflex.inference INFO: metric = R40
[2021-06-19 12:10:34,457] monoflex.inference INFO:
Car AP@0.70, 0.70, 0.70:
bbox AP:96.0539, 88.0300, 78.2660
bev  AP:19.1159, 16.3487, 14.0977
3d   AP:12.8832, 11.0194, 9.8003
aos  AP:95.71, 87.37, 77.32
```

**Comment by BigTeacher-777** [comment]
> @BigTeacher-777 去掉dla中的dcn，batch_size=6，单卡训练。val上结果：
> 
> ```
> [2021-06-19 12:10:34,456] monoflex.inference INFO: metric = R40
> [2021-06-19 12:10:34,457] monoflex.inference INFO:
> Car AP@0.70, 0.70, 0.70:
> bbox AP:96.0539, 88.0300, 78.2660
> bev  AP:19.1159, 16.3487, 14.0977
> 3d   AP:12.8832, 11.0194, 9.8003
> aos  AP:95.71, 87.37, 77.32
> ```

所以你还是没有得到跟paper相近的结果哈

**Comment by DuZzzs** [comment]
@BigTeacher-777 对比了下作者提供的log.txt，发现config里有些设置与之前代码不一致。准备更新下作者的代码重新跑下。

**Comment by BigTeacher-777** [comment]
> @BigTeacher-777 对比了下作者提供的log.txt，发现config里有些设置与之前代码不一致。准备更新下作者的代码重新跑下。

好的，如果有新的结果麻烦同步我一声哈，感谢

**Comment by skyhehe123** [comment]
@DuZzzs @zhangyp15 能否发一下新的log.txt给我（18106453r@connect.polyu.hk)， 我目前用单卡， batch size=8，跑下来跟你结果差不多

**Comment by DuZzzs** [comment]
@skyhehe123 readme里有啊。我pull了最新代码，单卡batch_size=8，torch和dcn升级到1.6，没跑完，结果不乐观。

**Comment by wsliu1999** [comment]
@DuZzzs 老哥你试过去掉DCN版本吗 效果咋样啊

**Comment by Owen-Liuyuxuan** [comment]
我用作者的repo和我自己的reimplementation在单卡上效果差不多。 validation的结果差不多是这样的(DLA34-DCN)
```
Car AP(Average Precision)@0.70, 0.70, 0.70:
bbox AP:96.69, 88.86, 78.83
bev  AP:26.54, 20.12, 16.64
3d   AP:19.17, 14.06, 11.24
aos  AP:96.43, 88.43, 78.20
Car AP(Average Precision)@0.70, 0.50, 0.50:
bbox AP:96.69, 88.86, 78.83
bev  AP:63.16, 46.87, 40.08
3d   AP:56.62, 42.81, 36.39
aos  AP:96.43, 88.43, 78.20

Pedestrian AP(Average Precision)@0.50, 0.50, 0.50:
bbox AP:67.23, 55.42, 45.80
bev  AP:6.05, 4.59, 3.72
3d   AP:4.61, 3.34, 2.78
aos  AP:54.99, 45.09, 37.27
Pedestrian AP(Average Precision)@0.50, 0.25, 0.25:
bbox AP:67.23, 55.42, 45.80
bev  AP:25.83, 20.45, 17.04
3d   AP:24.42, 20.14, 16.78
aos  AP:54.99, 45.09, 37.27

Cyclist AP(Average Precision)@0.50, 0.50, 0.50:
bbox AP:81.29, 49.84, 47.35
bev  AP:6.54, 3.67, 3.54
3d   AP:6.28, 3.56, 3.39
aos  AP:73.14, 44.37, 42.08
Cyclist AP(Average Precision)@0.50, 0.25, 0.25:
bbox AP:81.29, 49.84, 47.35
bev  AP:26.47, 14.74, 13.48
3d   AP:25.79, 14.22, 13.11
aos  AP:73.14, 44.37, 42.08
```

**Comment by Ferdinand-Byte** [comment]
> 您好，我在kitti-split1上用单卡进行训练，batch_size=4，在val的3694张图上测试：
> 
> ```
> [2021-06-17 06:25:15,960] monoflex.inference INFO: metric = R40
> [2021-06-17 06:25:15,961] monoflex.inference INFO:
> Car AP@0.70, 0.70, 0.70:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:27.4066, 19.9626, 16.8124
> 3d   AP:19.3602, 13.9580, 11.9678
> aos  AP:93.01, 87.77, 79.92
> Car AP@0.70, 0.50, 0.50:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:61.1731, 45.9274, 40.7388
> 3d   AP:55.3238, 41.9672, 35.9666
> aos  AP:93.01, 87.77, 79.92


> Pedestrian AP@0.50, 0.50, 0.50:
> bbox AP:52.8775, 44.4330, 37.8220
> bev  AP:6.5744, 5.0258, 4.0656
> 3d   AP:5.9074, 4.2190, 3.2233
> aos  AP:46.37, 38.43, 32.49
> Pedestrian AP@0.50, 0.25, 0.25:
> bbox AP:52.8775, 44.4330, 37.8220
> bev  AP:21.2798, 17.0815, 13.9071
> 3d   AP:20.5831, 16.5574, 13.3822
> aos  AP:46.37, 38.43, 32.49
> Cyclist AP@0.50, 0.50, 0.50:
> bbox AP:55.2721, 36.1850, 33.6507
> bev  AP:1.5678, 0.8645, 0.7968
> 3d   AP:1.2153, 0.3637, 0.3799
> aos  AP:47.42, 30.75, 28.57
> Cyclist AP@0.50, 0.25, 0.25:
> bbox AP:55.2721, 36.1850, 33.6507
> bev  AP:11.4607, 5.7936, 5.4553
> 3d   AP:10.6146, 5.3862, 4.8811
> aos  AP:47.42, 30.75, 28.57
> 
> [2021-06-17 06:25:16,132] monoflex.trainer INFO: Total training time: 21:24:51.903272 (0.8307 s / it), best model is achieved at iteration = 91872
> ```
> 
> 低于论文中Table1的val ap3d_r40,：23.64 17.51 14.83，相差4个点左右。请问是我哪里设置的不对吗？谢========================my question===================================================
你好，我还没跑通，先问一下编译DCN的gcc版本你用的是多少？
 Car AP@0.70, 0.70, 0.70:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:27.4066, 19.9626, 16.8124
> 3d   AP:19.3602, 13.9580, 11.9678
> aos  AP:93.01, 87.77, 79.92
==========以车类为例为什么有两个不同的结果，上面和下面数据准度区别那么大，为啥====================
> Car AP@0.70, 0.50, 0.50:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:61.1731, 45.9274, 40.7388
> 3d   AP:55.3238, 41.9672, 35.9666
> aos  AP:93.01, 87.77, 79.92
=============谢谢答疑


> 您好，我在kitti-split1上用单卡进行训练，batch_size=4，在val的3694张图上测试：
> 
> ```
> [2021-06-17 06:25:15,960] monoflex.inference INFO: metric = R40
> [2021-06-17 06:25:15,961] monoflex.inference INFO:
> Car AP@0.70, 0.70, 0.70:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:27.4066, 19.9626, 16.8124
> 3d   AP:19.3602, 13.9580, 11.9678
> aos  AP:93.01, 87.77, 79.92
> Car AP@0.70, 0.50, 0.50:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:61.1731, 45.9274, 40.7388
> 3d   AP:55.3238, 41.9672, 35.9666
> aos  AP:93.01, 87.77, 79.92
> Pedestrian AP@0.50, 0.50, 0.50:
> bbox AP:52.8775, 44.4330, 37.8220
> bev  AP:6.5744, 5.0258, 4.0656
> 3d   AP:5.9074, 4.2190, 3.2233
> aos  AP:46.37, 38.43, 32.49
> Pedestrian AP@0.50, 0.25, 0.25:
> bbox AP:52.8775, 44.4330, 37.8220
> bev  AP:21.2798, 17.0815, 13.9071
> 3d   AP:20.5831, 16.5574, 13.3822
> aos  AP:46.37, 38.43, 32.49
> Cyclist AP@0.50, 0.50, 0.50:
> bbox AP:55.2721, 36.1850, 33.6507
> bev  AP:1.5678, 0.8645, 0.7968
> 3d   AP:1.2153, 0.3637, 0.3799
> aos  AP:47.42, 30.75, 28.57
> Cyclist AP@0.50, 0.25, 0.25:
> bbox AP:55.2721, 36.1850, 33.6507
> bev  AP:11.4607, 5.7936, 5.4553
> 3d   AP:10.6146, 5.3862, 4.8811
> aos  AP:47.42, 30.75, 28.57
> 
> [2021-06-17 06:25:16,132] monoflex.trainer INFO: Total training time: 21:24:51.903272 (0.8307 s / it), best model is achieved at iteration = 91872
> ```
> 
> 低于论文中Table1的val ap3d_r40,：23.64 17.51 14.83，相差4个点左右。请问是我哪里设置的不对吗？谢谢

**Comment by Ferdinand-Byte** [comment]
> 您好，我在kitti-split1上用单卡进行训练，batch_size=4，在val的3694张图上测试：
> 
> ```
> [2021-06-17 06:25:15,960] monoflex.inference INFO: metric = R40
> [2021-06-17 06:25:15,961] monoflex.inference INFO:
> Car AP@0.70, 0.70, 0.70:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:27.4066, 19.9626, 16.8124
> 3d   AP:19.3602, 13.9580, 11.9678
> aos  AP:93.01, 87.77, 79.92
> Car AP@0.70, 0.50, 0.50:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:61.1731, 45.9274, 40.7388
> 3d   AP:55.3238, 41.9672, 35.9666
> aos  AP:93.01, 87.77, 79.92
> Pedestrian AP@0.50, 0.50, 0.50:
> bbox AP:52.8775, 44.4330, 37.8220
> bev  AP:6.5744, 5.0258, 4.0656
> 3d   AP:5.9074, 4.2190, 3.2233
> aos  AP:46.37, 38.43, 32.49
> Pedestrian AP@0.50, 0.25, 0.25:
> bbox AP:52.8775, 44.4330, 37.8220
> bev  AP:21.2798, 17.0815, 13.9071
> 3d   AP:20.5831, 16.5574, 13.3822
> aos  AP:46.37, 38.43, 32.49
> Cyclist AP@0.50, 0.50, 0.50:
> bbox AP:55.2721, 36.1850, 33.6507
> bev  AP:1.5678, 0.8645, 0.7968
> 3d   AP:1.2153, 0.3637, 0.3799
> aos  AP:47.42, 30.75, 28.57
> Cyclist AP@0.50, 0.25, 0.25:
> bbox AP:55.2721, 36.1850, 33.6507
> bev  AP:11.4607, 5.7936, 5.4553
> 3d   AP:10.6146, 5.3862, 4.8811
> aos  AP:47.42, 30.75, 28.57
> 
> [2021-06-17 06:25:16,132] monoflex.trainer INFO: Total training time: 21:24:51.903272 (0.8307 s / it), best model is achieved at iteration = 91872
> ```
> 
> 低于论文中Table1的val ap3d_r40,：23.64 17.51 14.83，相差4个点左右。请问是我哪里设置的不对吗？谢谢
========================my question===================================================
你好，我还没跑通，先问一下编译DCN的gcc版本你用的是多少？
 Car AP@0.70, 0.70, 0.70:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:27.4066, 19.9626, 16.8124
> 3d   AP:19.3602, 13.9580, 11.9678
> aos  AP:93.01, 87.77, 79.92
==========以车类为例为什么有两个不同的结果，上面和下面数据准度区别那么大，为啥====================
> Car AP@0.70, 0.50, 0.50:
> bbox AP:93.1365, 88.1290, 80.6364
> bev  AP:61.1731, 45.9274, 40.7388
> 3d   AP:55.3238, 41.9672, 35.9666
> aos  AP:93.01, 87.77, 79.92
=============谢谢答疑
